using Content.Client._Floof.Paint;
using Content.Client.Lobby.UI.Loadouts;
using Content.Client.UserInterface.Controls;
using Content.Shared._Floof.Paint;
using Content.Shared.Clothing;
using Content.Shared.Preferences.Loadouts;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Floof.Lobby.UI;

[GenerateTypedNameReferences]
public sealed partial class LoadoutMetadataEditorDialog : FancyWindow
{
    [Dependency] private IEntitySystemManager _entSys = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    public event Action<(Loadout loadout, bool copyMetadata, bool copyLoadout)>? OnSave;

    private readonly ProtoId<LoadoutPrototype> _loadoutProto;
    private readonly ProtoId<LoadoutGroupPrototype> _groupProto;
    private Loadout _loadout;
    private LoadoutContainer _previewContainer = default!;

    public LoadoutMetadataEditorDialog(
        Loadout currentState,
        ProtoId<LoadoutPrototype> loadoutProto,
        ProtoId<LoadoutGroupPrototype> groupProto)
    {
        IoCManager.InjectDependencies(this);
        _entSys.TryGetEntitySystem<LoadoutSystem>(out var loadoutSystem);
        _protoMan.TryIndex(loadoutProto, out var loadoutProtoResolved);

        _loadoutProto = loadoutProto;
        _groupProto = groupProto;
        RobustXamlLoader.Load(this);

        // Working copy so cancel doesn't pollute the profile
        _loadout = new Loadout(currentState);

        _previewContainer = new LoadoutContainer(loadoutProto, true, FormattedMessage.FromMarkupPermissive("Preview"));
        _previewContainer.Text = _loadout.NameOverride
            ?? (loadoutProtoResolved != null ? loadoutSystem?.GetName(loadoutProtoResolved) : "<error>");
        LoadoutPreviewContainer.AddChild(_previewContainer);

        Load(_loadout);

        CancelButton.OnPressed += _ => Close();
        SaveButton.OnPressed += _ =>
        {
            Save();
            Close();
        };

        CustomColorEnabled.OnToggled += args =>
        {
            ColorSelector.Visible = args.Pressed;
        };

        ColorSelector.OnColorChanged += color =>
        {
            ColorEntity(_previewContainer.SpriteEntity, color, _entMan);
        };

        CopyMetadataToAllCheckbox.OnToggled += args =>
        {
            // "Copy loadout" only makes sense when "apply metadata to all" is on
            CopyLoadoutToAllCheckbox.Pressed = false;
            CopyLoadoutToAllCheckbox.Disabled = !args.Pressed;
        };
    }

    public void Load(Loadout currentState)
    {
        CustomNameField.Text = currentState.NameOverride ?? string.Empty;
        CustomDescField.Text = currentState.DescriptionOverride ?? string.Empty;

        CustomColorEnabled.Pressed = currentState.ColorOverride != null;
        ColorSelector.Visible = CustomColorEnabled.Pressed;
        ColorSelector.Color = currentState.ColorOverride is { Length: > 0 } customColor
            ? Color.FromHex(customColor, Color.White)
            : Color.White;

        ColorEntity(_previewContainer.SpriteEntity, currentState.ColorOverride, _entMan);
    }

    public void Save(bool raiseEvent = true)
    {
        string? customName = CustomNameField.Text.Trim();
        string? customDesc = CustomDescField.Text.Trim();
        Color? customColor = CustomColorEnabled.Pressed ? ColorSelector.Color : null;

        if (customName.Length == 0)
            customName = null;
        if (customDesc.Length == 0)
            customDesc = null;

        // Prevent pure-black / near-black items that are unreadable
        if (customColor != null)
            customColor = SharedColorPaintSystem.ClampBrightness(customColor.Value, 0.25f, 1f);

        _loadout.NameOverride = customName;
        _loadout.DescriptionOverride = customDesc;
        _loadout.ColorOverride = customColor?.ToHexNoAlpha();

        if (raiseEvent)
        {
            var copyMetadata = CopyMetadataToAllCheckbox.Pressed;
            var copyLoadout = copyMetadata && CopyLoadoutToAllCheckbox.Pressed;
            OnSave?.Invoke((_loadout, copyMetadata, copyLoadout));
        }

        Load(_loadout);
    }

    public static void ColorEntity(EntityUid? ent, string? color, IEntityManager entMan)
    {
        Color? c = color == null ? null : Color.FromHex(color, Color.White);
        ColorEntity(ent, c, entMan);
    }

    public static void ColorEntity(EntityUid? ent, Color? color, IEntityManager entMan)
    {
        if (!entMan.EntityExists(ent) || entMan.Deleted(ent))
            return;

        if (color == null && !entMan.HasComponent<ColorPaintedComponent>(ent)
            || !entMan.TrySystem<ColorPaintSystem>(out var colorPaint))
            return;

        if (color != null)
            colorPaint.Paint(null, null, ent.Value, color.Value);
        else
            colorPaint.ClearPaint(ent.Value);
    }
}
